services:
  - type: web
    name: credmarket
    env: python
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn credmarket.wsgi:application --log-file - --log-level debug --capture-output --access-logfile - --error-logfile -"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: credmarket-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: credmarket.onrender.com
      - key: SITE_URL
        value: https://credmarket.onrender.com
      - key: EMAIL_HOST
        value: smtp.resend.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_HOST_USER
        value: resend
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: onboarding@resend.dev
    autoDeploy: true

databases:
  - name: credmarket-db
    databaseName: credmarket
    user: credmarket
